# Generated by Django 4.0.3 on 2024-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentclean'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='datetime_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclean',
            name='datetime_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
