# Generated by Django 4.0.3 on 2023-12-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_datetime_studentclean_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='datetime',
            new_name='datetime_data',
        ),
        migrations.RenameField(
            model_name='studentclean',
            old_name='datetime',
            new_name='datetime_data',
        ),
    ]
