# Generated by Django 4.0.3 on 2024-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentclean',
            name='roll',
            field=models.CharField(max_length=20),
        ),
    ]
