# Generated by Django 4.0.3 on 2024-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_city_alter_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.TextField(blank=True, null=True, unique=True)),
                ('agent_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingCleaned_with_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.TextField(blank=True, null=True, unique=True)),
                ('listing_mls_id', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('acre', models.CharField(blank=True, max_length=20, null=True)),
                ('agents', models.ManyToManyField(related_name='properties_of_listing', to='school.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='properties',
            field=models.ManyToManyField(related_name='agents_of_property', to='school.listingcleaned_with_relation'),
        ),
    ]
