# Generated by Django 4.0.3 on 2024-01-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_agent_listingcleaned_with_relation_agent_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingcleaned_with_relation',
            name='agents',
        ),
    ]
