# Generated by Django 4.0.3 on 2024-01-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_listingcleaned_with_relation_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.TextField(blank=True, null=True, unique=True)),
                ('agent_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.TextField(blank=True, null=True, unique=True)),
                ('listing_mls_id', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('acre', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
