# Generated by Django 4.0.3 on 2024-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_rename_raw_agent_clean_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='listing_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='listing_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
