# Generated by Django 4.0.3 on 2024-01-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_agent_listing_id_alter_properties_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, related_name='agents_of_property', to='school.properties'),
        ),
    ]
